EventsAlumni/force-app/main/default/objects/Event_Booking__c/Event_Booking__c.object-meta.xml
<CustomObject>
    <label>Event Booking</label>
    <nameField>
        <displayFormat>EB-{00000}</displayFormat>
        <label>Event Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EventsAlumni/force-app/main/default/objects/Event_Booking__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Event Bookings</relationshipLabel>
    <relationshipName>Event_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Booking__c/fields/Billing_Details__c.field-meta.xml
<CustomField>
    <fullName>Billing_Details__c</fullName>
    <label>Billing Details</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Booking__c/fields/Booked_for_No_of_Attendees__c.field-meta.xml
<CustomField>
    <fullName>Booked_for_No_of_Attendees__c</fullName>
    <label>Booked for No of Attendees</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Booking__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Bookings</relationshipLabel>
    <relationshipName>Event_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Booking__c/fields/Event_Booking_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Booking_Id__c</fullName>
    <label>Event Booking Id</label>
    <type>AutoNumber</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Booking__c/fields/Schedule_Sessions_Id__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Sessions_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule/Sessions Id</label>
    <referenceTo>Schedule_Sessions__c</referenceTo>
    <relationshipLabel>Event Bookings (Schedule/Sessions Id)</relationshipLabel>
    <relationshipName>Event_Bookings1</relationshipName>
    <type>Lookup</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Booking__c/fields/Schedules_Sessions__c.field-meta.xml
<CustomField>
    <fullName>Schedules_Sessions__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedules &amp; Sessions</label>
    <referenceTo>Schedule_Sessions__c</referenceTo>
    <relationshipLabel>Event Bookings</relationshipLabel>
    <relationshipName>Event_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Booking__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Notify</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Master__c/Event_Master__c.object-meta.xml
<CustomObject>
    <label>Event Master</label>
    <nameField>
        <label>Events/Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Master Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EventsAlumni/force-app/main/default/objects/Event_Master__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Master Setup</relationshipLabel>
    <relationshipName>Event_Master_Setup</relationshipName>
    <type>Lookup</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Master__c/fields/Event_banner__c.field-meta.xml
<CustomField>
    <fullName>Event_banner__c</fullName>
    <label>Event banner</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Master__c/fields/Event_Broucher__c.field-meta.xml
<CustomField>
    <fullName>Event_Broucher__c</fullName>
    <label>Event Broucher</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Master__c/fields/Event_Current_Step__c.field-meta.xml
<CustomField>
    <fullName>Event_Current_Step__c</fullName>
    <label>Event Current Step</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Master__c/fields/Event_Fee__c.field-meta.xml
<CustomField>
    <fullName>Event_Fee__c</fullName>
    <label>Event Fee</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Master__c/fields/Event_Group_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Group_Id__c</fullName>
    <label>Event Group Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Master__c/fields/Event_Status__c.field-meta.xml
<CustomField>
    <fullName>Event_Status__c</fullName>
    <label>Event Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Master__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <label>Event Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cultural</fullName>
            </value>
            <value>
                <fullName>Sports</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
            <value>
                <fullName>Academic</fullName>
            </value>
            <value>
                <fullName>Outreach</fullName>
            </value>
            <value>
                <fullName>Orientation</fullName>
            </value>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>Literature</fullName>
            </value>
            <value>
                <fullName>Wellness</fullName>
            </value>
            <value>
                <fullName>Charity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Master__c/fields/Evvent_Group__c.field-meta.xml
<CustomField>
    <fullName>Evvent_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Group</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Event_Master__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Event Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Event_Master__c</referenceTo>
    <relationshipLabel>Event Masters</relationshipLabel>
    <relationshipName>Event_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Master__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active?</label>
    <type>Checkbox</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Master__c/fields/Is_All_Day__c.field-meta.xml
<CustomField>
    <fullName>Is_All_Day__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is All Day?</label>
    <type>Checkbox</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Master__c/fields/Is_Archived__c.field-meta.xml
<CustomField>
    <fullName>Is_Archived__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Archived?</label>
    <type>Checkbox</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Master__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Hindi</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Master__c/fields/Max_Allowed_Participants__c.field-meta.xml
<CustomField>
    <fullName>Max_Allowed_Participants__c</fullName>
    <label>Max Allowed Participants</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Master__c/fields/Target_Keywords__c.field-meta.xml
<CustomField>
    <fullName>Target_Keywords__c</fullName>
    <label>Target Keywords</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Master__c/fields/What_to_Expect_From_Event__c.field-meta.xml
<CustomField>
    <fullName>What_to_Expect_From_Event__c</fullName>
    <label>What to Expect From Event?</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Master__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <label>Event</label>
</RecordType>

EventsAlumni/force-app/main/default/objects/Schedule_Sessions__c/Schedule_Sessions__c.object-meta.xml
<CustomObject>
    <label>Schedule &amp; Sessions</label>
    <nameField>
        <label>Schedule/Sessions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule &amp; Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EventsAlumni/force-app/main/default/objects/Schedule_Sessions__c/fields/Column__c.field-meta.xml
<CustomField>
    <fullName>Column__c</fullName>
    <label>Column</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Schedule_Sessions__c/fields/Event_Reference__c.field-meta.xml
<CustomField>
    <fullName>Event_Reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Reference</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Event_Master__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Event</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Event_Master__c</referenceTo>
    <relationshipName>Schedule_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Schedule_Sessions__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <label>Event Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Conferences</fullName>
            </value>
            <value>
                <fullName>Seminars</fullName>
            </value>
            <value>
                <fullName>Graduation Parties</fullName>
            </value>
            <value>
                <fullName>Religious Gatherings</fullName>
            </value>
            <value>
                <fullName>Exhibitions</fullName>
            </value>
            <value>
                <fullName>Team Onsites</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

EventsAlumni/force-app/main/default/objects/Schedule_Sessions__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <label>Is Active?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

EventsAlumni/force-app/main/default/objects/Schedule_Sessions__c/fields/Is_Archived__c.field-meta.xml
<CustomField>
    <fullName>Is_Archived__c</fullName>
    <label>Is Archived?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

EventsAlumni/force-app/main/default/objects/Schedule_Sessions__c/fields/Is_Scheduled__c.field-meta.xml
<CustomField>
    <fullName>Is_Scheduled__c</fullName>
    <label>Is Scheduled?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

EventsAlumni/force-app/main/default/objects/Schedule_Sessions__c/fields/No_Fee__c.field-meta.xml
<CustomField>
    <fullName>No_Fee__c</fullName>
    <defaultValue>false</defaultValue>
    <label>No Fee</label>
    <type>Checkbox</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Schedule_Sessions__c/fields/Schedule_Sessions_Id__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Sessions_Id__c</fullName>
    <displayFormat>Session#{000}</displayFormat>
    <label>Schedule/Sessions Id</label>
    <type>AutoNumber</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Schedule_Sessions__c/fields/Target_Keywords__c.field-meta.xml
<CustomField>
    <fullName>Target_Keywords__c</fullName>
    <label>Target Keywords</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Schedule_Sessions__c/fields/What_to_Expect_From_Event__c.field-meta.xml
<CustomField>
    <fullName>What_to_Expect_From_Event__c</fullName>
    <label>What to Expect From Event?</label>
    <type>TextArea</type>
</CustomField>

EventsAlumni/force-app/main/default/classes/ken42_EventManagementHandler.cls
@RestResource(urlMapping='/eventManagementHandler/*')
global with sharing class ken42_EventManagementHandler {
	 @HttpGET
    global static String eventGetMethod(){
        List<Event_Master__c> allEvents = [SELECT Id, Name,Event_Current_Step__c,Language__c,Target_Keywords__c,Event_Status__c,Event_Broucher__c,Description__c,createdDate,Event_Fee__c,No_Fee__c, RecordTypeId, End_Date__c, End_Time__c, Event_Group_Id__c, Event_Type__c, Event_banner__c, Evvent_Group__c, Is_Archived__c, Is_Scheduled__c, Is_Active__c, Location__c, Max_Allowed_Participants__c, Start_Date__c, Start_Time__c, Title__c, What_to_Expect_From_Event__c FROM Event_Master__c];
         List<EventWrapper> eventWrappers = new List<EventWrapper>();

        Date today = Date.today();

        for (Event_Master__c event : allEvents) {
            Boolean isUpcoming = false;
            Boolean isPast = false;
            Boolean isInProgress = false;
            Boolean isCompleted = false;
            Boolean isCancel = false;
            Boolean isPending = false;
            
            if (event.Event_Status__c == 'In Progress') {
                isInProgress = true;
            } else if (event.Event_Status__c == 'Completed') {
                isCompleted = true;
            } else if (event.Event_Status__c == 'Cancel') {
                isCancel = true;
            } else if (event.Event_Status__c == 'Pending') {
                isPending =true;
            }
            
            if (event.Start_Date__c >= today) {
                isUpcoming = true;
            }

            // Set isPast based on start date
            if (event.Start_Date__c < today) {
                isPast = true;
            }
            
            // Create a wrapper object and add it to the list
            EventWrapper eventWrapper = new EventWrapper(event, isUpcoming, isPast, isInProgress, isCompleted, isCancel, isPending);
            eventWrappers.add(eventWrapper);
        }

        // Return the list of event wrappers
        return JSON.serialize(eventWrappers);
    }
    @HttpPOST
    global static void eventPostMethod(){
        System.debug(RestContext.request.requestBody.toString());
        eventHandler(RestContext.request.requestBody.toString());
    }
    public static void eventHandler(String eventWrapperDetails){
      String eventBroucherURL = ' ';
      String eventBannerURL =' ';
        eventWrapper request = (eventWrapper) JSON.deserialize(
              eventWrapperDetails,
              eventWrapper.class
        );
      	System.debug(request.eventTitle);
        request.isEventBroucher = true;
        if((request?.eventBroucher !=null && request?.eventBroucher !='') && request?.isEventBroucher){
           eventBroucherURL = ken42_CreateContentVersion.createContentVersion(request.eventTitle, request.eventBroucher);
        }
        if((request?.coverImageURL !=null && request?.coverImageURL !='')){
           eventBannerURL = ken42_CreateContentVersion.createContentVersion(request.eventTitle+'Cover Image', request.coverImageURL);
        }
        List<Event_Master__c> eventMaster = [SELECT Id, Name, RecordTypeId, End_Date__c, End_Time__c, Event_Group_Id__c, Event_Type__c, Event_banner__c, Evvent_Group__c, Is_Archived__c, Is_Scheduled__c, Is_Active__c, Location__c, Max_Allowed_Participants__c, Start_Date__c, Start_Time__c, Title__c, What_to_Expect_From_Event__c FROM Event_Master__c];
        List<Event_Booking__c> eventBooking = [SELECT Id, Name, Account__c, Billing_Details__c, Booked_for_No_of_Attendees__c, Contact__c, Event_Booking_Id__c, Is_Active__c, Type__c, Schedules_Sessions__c, Schedule_Sessions_Id__c FROM Event_Booking__c];
        List<Schedule_Sessions__c> scheduleSession = [SELECT Id, Name, Column__c, End_Date__c, End_Time__c, Event_Reference__c, Event_Type__c, Is_Active__c, Is_All_Day__c, Is_Archived__c, Is_Scheduled__c, Location__c, Schedule_Sessions_Id__c, Session_Fee__c, Start_Date__c, Start_Time__c, Title__c, What_to_Expect_From_Event__c FROM Schedule_Sessions__c];
        
        Event_Master__c event = new Event_Master__c();
        if(request.eventTitle !=null && request.eventTitle !=''){
            event.Name = request.eventTitle;
        }
        if(request.category !=null && request.category !=''){
            event.Event_Type__c = request.category;
        }
        if(request.maximumNumberofParticipants !=null){
            event.Max_Allowed_Participants__c = request.maximumNumberofParticipants;
        }

        if(request.description !=null && request.description !=''){
            event.Description__c = request.description;
        }
        if(request.agenda !=null && request.agenda !=''){
           event.What_to_Expect_From_Event__c = request.agenda;
        }
        if(request.suitablefor !=null && request.suitablefor !=''){
            event.Target_Audience_Applicable__c	 = request.suitablefor;
        }
        if(request.languageOfDelivery !=null && request.languageOfDelivery !=''){
            event.Language__c = request.languageOfDelivery;
        }
        if(request.startDate !=null){
            event.Start_Date__c = request.startDate;
        }
		
        if(request.endDate !=null){
            event.End_Date__c = request.endDate;
        }
        
        if(request.startTime !=null){
            event.Start_Time__c = request.startTime;
        }
        
        if(request.endTime !=null){
            event.End_Time__c = request.endTime;
        }
        
        if(eventBroucherURL !=null && string.isNotBlank(eventBroucherURL)){
            event.Event_Broucher__c = eventBroucherURL;
        }
        
        if(eventBannerURL !=null && string.isNotBlank(eventBannerURL)){
            event.Event_banner__c = eventBannerURL;
        }
        
        if(request.currentStep !=null){
            event.Event_Current_Step__c = request.currentStep;
        }
        
        if(request.targetKeyWords !=null && request.targetKeyWords !=''){
            event.Target_Keywords__c = request.targetKeyWords;
        }
        
        if(string.isNotBlank(request?.Id)){
           event.Id = request.Id;
            update event;
          }
        	else{
                 insert event;   
                }
        eventResponse response = new eventResponse();
        response.eventId=event.Id;
        response.name = event.Name;
        response.coverImage = event.Event_banner__c;
        response.brochureImage = event.Event_Broucher__c;
        response.currentStep = event.Event_Current_Step__c;
        RestApiUtility.createSuccessPostResponse(response);
        
    }
    
    public class eventWrapper{
        public string Id;
        public string eventTitle;
        public String category;
        public Decimal maximumNumberofParticipants;
        public String description;
        public String agenda;
        public String targetKeyWords;
        public String suitablefor;
        public String languageOfDelivery;
        public String eventBroucher;
        public Boolean isEventBroucher;
        public Date startDate;
        public Date endDate;
        public Time startTime;
        public Time endTime;
        public String coverImageURL;
        public Decimal currentStep;
        public Boolean isUpcoming;
        public Boolean ispast;
        public Boolean isInprogress;
        public Boolean isCompleted;
        public Boolean isCancel;
        public Boolean isPending;
        public Decimal eventFee;
        public Boolean eventNoFee;
        public Datetime createdDate;
     	public EventWrapper(Event_Master__c event, Boolean isUpcoming, Boolean ispast, Boolean isInprogress, Boolean isCompleted, Boolean isCancel, Boolean isPenidng){
            this.Id = event.Id;
            this.eventTitle = event.Name;
            this.category = event.Event_Type__c;
            this.startdate = event.Start_Date__c;
            this.enddate = event.End_Date__c;
            this.startTime = event.Start_Time__c;
            this.endTime = event.End_Time__c;
            this.description = event.Description__c;
            this.agenda =event.What_to_Expect_From_Event__c;
            this.coverImageURL = event.Event_banner__c;
            this.eventBroucher = event.Event_Broucher__c;
            this.currentStep = event.Event_Current_Step__c;
            this.languageOfDelivery = event.Language__c;
            this.eventFee = event.Event_Fee__c;
            this.eventNoFee = event.No_Fee__c;
            this.maximumNumberofParticipants = event.Max_Allowed_Participants__c;
            this.targetKeyWords = event.Target_Keywords__c;
            this.createdDate = event.CreatedDate;   
            this.isUpcoming = isUpcoming;
            this.ispast = ispast;
            this.isInprogress = isInprogress;
            this.isCompleted = isCompleted; 
            this.isCancel = isCancel; 
            this.isPending = isPending;   
        }
    }
    
    public class eventResponse{
        public Id eventId;
        public String name;
        public string coverImage;
        public String brochureImage;
        public Decimal currentStep;
    }
    
   /* public class getEventWrapper{
         public Map<string, List<Event_Master__c>> events { get; set; }
       // public List<Contact> contacts { get; set; }
        
        public getEventWrapper(Map<string, List<Event_Master__c>>  events) {
            this.events = events;
            //this.contacts = contacts;
        }
    }*/
}