EventsAlumni/force-app/main/default/objects/Event_Booking__c/Event_Booking__c.object-meta.xml
<CustomObject>
    <label>Event Booking</label>
    <nameField>
        <displayFormat>EB-{00000}</displayFormat>
        <label>Event Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EventsAlumni/force-app/main/default/objects/Event_Booking__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Bookings</relationshipLabel>
    <relationshipName>Event_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Booking__c/fields/Schedule_Sessions_Id__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Sessions_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule/Sessions Id</label>
    <referenceTo>Schedule_Sessions__c</referenceTo>
    <relationshipLabel>Event Bookings (Schedule/Sessions Id)</relationshipLabel>
    <relationshipName>Event_Bookings1</relationshipName>
    <type>Lookup</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Booking__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Notify</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Master__c/Event_Master__c.object-meta.xml
<CustomObject>
    <label>Event Master</label>
    <nameField>
        <label>Events/Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Master Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EventsAlumni/force-app/main/default/objects/Event_Master__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Master Setup</relationshipLabel>
    <relationshipName>Event_Master_Setup</relationshipName>
    <type>Lookup</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Master__c/fields/Event_banner__c.field-meta.xml
<CustomField>
    <fullName>Event_banner__c</fullName>
    <label>Event banner</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Master__c/fields/Event_Group_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Group_Id__c</fullName>
    <label>Event Group Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Master__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <label>Event Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cultural</fullName>
            </value>
            <value>
                <fullName>Sports</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
            <value>
                <fullName>Academic</fullName>
            </value>
            <value>
                <fullName>Outreach</fullName>
            </value>
            <value>
                <fullName>Orientation</fullName>
            </value>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>Literature</fullName>
            </value>
            <value>
                <fullName>Wellness</fullName>
            </value>
            <value>
                <fullName>Charity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Master__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active?</label>
    <type>Checkbox</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Master__c/fields/Is_All_Day__c.field-meta.xml
<CustomField>
    <fullName>Is_All_Day__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is All Day?</label>
    <type>Checkbox</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Master__c/fields/Is_Archived__c.field-meta.xml
<CustomField>
    <fullName>Is_Archived__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Archived?</label>
    <type>Checkbox</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Master__c/fields/What_to_Expect_From_Event__c.field-meta.xml
<CustomField>
    <fullName>What_to_Expect_From_Event__c</fullName>
    <label>What to Expect From Event?</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Events_Sessions_Enrollment__c/Events_Sessions_Enrollment__c.object-meta.xml
<CustomObject>
    <label>Events &amp; Sessions - Enrollment</label>
    <nameField>
        <displayFormat>PO# {00000000}</displayFormat>
        <label>Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events &amp; Sessions - Enrollment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EventsAlumni/force-app/main/default/objects/Events_Sessions_Enrollment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Event_Session_Account_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Events_Sessions_Enrollment__c/fields/Booking_ID__c.field-meta.xml
<CustomField>
    <fullName>Booking_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking ID</label>
    <referenceTo>Event_Booking__c</referenceTo>
    <relationshipName>Event_Session_Account_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Events_Sessions_Enrollment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Event_Session_Account_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Events_Sessions_Enrollment__c/fields/Event_Reference__c.field-meta.xml
<CustomField>
    <fullName>Event_Reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Reference</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Event_Master__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Event</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Event_Master__c</referenceTo>
    <relationshipLabel>Events &amp; Sessions - Enrollment</relationshipLabel>
    <relationshipName>Events_Sessions_Enrollment</relationshipName>
    <type>Lookup</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Events_Sessions_Enrollment__c/fields/Schedule_Sessions__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Sessions__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule/Sessions</label>
    <referenceTo>Schedule_Sessions__c</referenceTo>
    <relationshipName>Event_Session_Account_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Events_Sessions_Enrollment__c/fields/Speaker_Image__c.field-meta.xml
<CustomField>
    <fullName>Speaker_Image__c</fullName>
    <label>Speaker Image</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Events_Sessions_Enrollment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Notify</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

EventsAlumni/force-app/main/default/objects/Schedule_Sessions__c/Schedule_Sessions__c.object-meta.xml
<CustomObject>
    <label>Schedule &amp; Sessions</label>
    <nameField>
        <label>Schedule/Sessions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule &amp; Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EventsAlumni/force-app/main/default/objects/Schedule_Sessions__c/fields/Column__c.field-meta.xml
<CustomField>
    <fullName>Column__c</fullName>
    <label>Column</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Schedule_Sessions__c/fields/Event_Reference__c.field-meta.xml
<CustomField>
    <fullName>Event_Reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Reference</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Event_Master__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Event</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Event_Master__c</referenceTo>
    <relationshipName>Schedule_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Schedule_Sessions__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <label>Event Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Conferences</fullName>
            </value>
            <value>
                <fullName>Seminars</fullName>
            </value>
            <value>
                <fullName>Graduation Parties</fullName>
            </value>
            <value>
                <fullName>Religious Gatherings</fullName>
            </value>
            <value>
                <fullName>Exhibitions</fullName>
            </value>
            <value>
                <fullName>Team Onsites</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

EventsAlumni/force-app/main/default/objects/Schedule_Sessions__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <label>Is Active?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

EventsAlumni/force-app/main/default/objects/Schedule_Sessions__c/fields/Is_All_Day__c.field-meta.xml
<CustomField>
    <fullName>Is_All_Day__c</fullName>
    <label>Is All Day?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

EventsAlumni/force-app/main/default/objects/Schedule_Sessions__c/fields/Is_Archived__c.field-meta.xml
<CustomField>
    <fullName>Is_Archived__c</fullName>
    <label>Is Archived?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

EventsAlumni/force-app/main/default/objects/Schedule_Sessions__c/fields/Is_Scheduled__c.field-meta.xml
<CustomField>
    <fullName>Is_Scheduled__c</fullName>
    <label>Is Scheduled?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

EventsAlumni/force-app/main/default/objects/Schedule_Sessions__c/fields/Location_Type__c.field-meta.xml
<CustomField>
    <fullName>Location_Type__c</fullName>
    <label>Location Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Schedule_Sessions__c/fields/No_Fee__c.field-meta.xml
<CustomField>
    <fullName>No_Fee__c</fullName>
    <defaultValue>false</defaultValue>
    <label>No Fee</label>
    <type>Checkbox</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Schedule_Sessions__c/fields/Schedule_Sessions_Id__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Sessions_Id__c</fullName>
    <displayFormat>Session#{000}</displayFormat>
    <label>Schedule/Sessions Id</label>
    <type>AutoNumber</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Schedule_Sessions__c/fields/Session_Fee__c.field-meta.xml
<CustomField>
    <fullName>Session_Fee__c</fullName>
    <label>Session Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Schedule_Sessions__c/fields/Session_Link__c.field-meta.xml
<CustomField>
    <fullName>Session_Link__c</fullName>
    <label>Session Link</label>
    <type>TextArea</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Schedule_Sessions__c/fields/What_to_Expect_From_Event__c.field-meta.xml
<CustomField>
    <fullName>What_to_Expect_From_Event__c</fullName>
    <label>What to Expect From Event?</label>
    <type>TextArea</type>
</CustomField>

EventsAlumni/force-app/main/default/classes/ken42_ScheduleSessionHandler.cls
@RestResource(urlMapping='/scheduleSessionHandler/*')
global with sharing class ken42_ScheduleSessionHandler {
     @HttpGET
    global static string sessionGetMethod(){
         RestRequest req = RestContext.request;
        String eventId = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
        System.debug('eventId=='+eventId);
        if (String.isEmpty(eventId)) {
            throw new IllegalArgumentException('eventId must be provided.');
        }
        List<Schedule_Sessions__c> scheduleSessions = [SELECT Id, Name, Column__c,Location_Type__c,Session_Link__c, No_Fee__c,Session_Fee__c,End_Date__c, End_Time__c,(SELECT Id, Contact__r.Name,Contact__c,Speaker_Image__c, Description__c,Schedule_Sessions__c FROM Event_Session_Account_Associations__r) Event_Reference__c, Event_Type__c, Is_Active__c, Is_All_Day__c, Is_Archived__c, Is_Scheduled__c, Location__c, Schedule_Sessions_Id__c, Start_Date__c, Start_Time__c, Title__c, What_to_Expect_From_Event__c FROM Schedule_Sessions__c WHERE Event_Reference__c=:eventId];
        
        //Contacts List
         List<Contact> contactList = [
            SELECT Id, FirstName, LastName, Email, Phone 
            FROM Contact 
        ];
        
        getWrapper result = new getWrapper(scheduleSessions, contactList);
   		 return JSON.serialize(result);
    }
   @HttpDELETE
    global static void deleteSessions() {
        // Get the incoming request
        RestRequest req = RestContext.request;
        System.debug('req'+req);
        if (req.requestBody != null) {
            System.debug('req.requestBody'+req.requestBody);
            sessionIds deleteRecords = (sessionIds) JSON.deserialize(req.requestBody.toString(), sessionIds.class);
            System.debug('deleteRecords'+deleteRecords);
            
            List<Schedule_Sessions__c> scheduleSession = [SELECT Id, Name FROM Schedule_Sessions__c WHERE Id IN :deleteRecords.ids];
            
            if (scheduleSession.size() > 0) {
                delete scheduleSession;
            }
        } else {
            
            RestContext.response.statusCode = 400;
            RestContext.response.responseBody = Blob.valueOf('Invalid request: No session IDs provided.');
        }
    }

    
	 @HttpPOST
    global static void eventPostMethod(){
        System.debug(RestContext.request.requestBody.toString());
        scheduleSessionHandler(RestContext.request.requestBody.toString());
    }
    
     @HttpPATCH
    global static void eventPatchMethod(){
        System.debug(RestContext.request.requestBody.toString());
        updateScheduleSession(RestContext.request.requestBody.toString());
    }
    
    //POST METHOD
    public static void scheduleSessionHandler(String scheduleSessionWrapperDetails){
     
     List <sessionResponse> responseList = new List<sessionresponse>();
     List<Schedule_Sessions__c> sessionList = new List<Schedule_Sessions__c>();   
        List<scheduleSessionWrapper> request;
      try {
         request = (List<scheduleSessionWrapper>) JSON.deserialize(
            scheduleSessionWrapperDetails,
            List<scheduleSessionWrapper>.class
        );
    } catch (Exception e) {
        System.debug('Error deserializing JSON: ' + e.getMessage());
        throw new IllegalArgumentException('Invalid JSON format: ' + e.getMessage());
    }
       
        
        List<Event_Master__c> eventMaster = [SELECT Id, Name, RecordTypeId, End_Date__c, End_Time__c, Event_Group_Id__c, Event_Type__c, Event_banner__c, Evvent_Group__c, Is_Archived__c, Is_Scheduled__c, Is_Active__c, Location__c, Max_Allowed_Participants__c, Start_Date__c, Start_Time__c, Title__c, What_to_Expect_From_Event__c FROM Event_Master__c];
        List<Event_Booking__c> eventBooking = [SELECT Id, Name, Account__c, Billing_Details__c, Booked_for_No_of_Attendees__c, Contact__c, Event_Booking_Id__c, Is_Active__c, Type__c, Schedules_Sessions__c, Schedule_Sessions_Id__c FROM Event_Booking__c];
        //---------------------------------------------------------------------------------------------------------------------------------
           fflib_SObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(new Schema.SObjectType[] {
                Schedule_Sessions__c.SObjectType,
                Events_Sessions_Enrollment__c.SObjectType
          });
        
        for (scheduleSessionWrapper eachEventSchedule : request) {
            
            System.debug('deserializespeaker----'+eachEventSchedule.speakers);
            
                
            
            Schedule_Sessions__c singleEventSchedule = eachEventSchedule.getRecord();
      
            	/*sessionResponse response = new sessionResponse();
                response.sessionId = singleEventSchedule.Id;
                response.sessionTitle = singleEventSchedule.Name;
                response.sessionImage = singleEventSchedule.Session_Broucher__c;
                responseList.add(response);*/
            
           if (String.isNotBlank(singleEventSchedule?.Id)) {
                // Register existing record for update
                uow.registerDirty(singleEventSchedule);
               sessionList.add(singleEventSchedule);
            } else {
                // Register new record for insertion
                uow.registerNew(singleEventSchedule);
                sessionList.add(singleEventSchedule);
            }
            if(eachEventSchedule.speakers!=null){
                
                      
            for (SpeakerWrapper speaker : eachEventSchedule.speakers) {
                System.debug('Speaker Name: ' + speaker.Id);
                System.debug('Speaker Description: ' + speaker.descriptionAboutTheSpeaker);
                Events_Sessions_Enrollment__c sessionSpeakerEnrollment = speaker.getSessionEnrollmentRecord();
                if (String.isNotBlank(singleEventSchedule?.Id)) {
                	sessionSpeakerEnrollment.Schedule_Sessions__c = singleEventSchedule?.Id;
                }
                 if (String.isNotBlank(sessionSpeakerEnrollment?.Id)) {
                    uow.registerDirty(sessionSpeakerEnrollment);
                } else {
                    	sessionSpeakerEnrollment.Schedule_Sessions__c = singleEventSchedule.Id;
                        uow.registerNew(sessionSpeakerEnrollment, Events_Sessions_Enrollment__c.Schedule_Sessions__c, singleEventSchedule);
                }
            }
            }	      
        }
        System.debug('before comit sessionList--'+sessionList);
        uow.commitWork();
        System.debug('sessionList--'+sessionList);
    //Post Commit to send response backk
    for(Schedule_Sessions__c eachsession:sessionList){
        sessionResponse response = new sessionResponse();
                response.sessionId = eachsession.Id;
                response.sessionTitle = eachsession.Name;
                response.sessionImage = eachsession.Session_Broucher__c;
                responseList.add(response);
    }
        
   
        RestApiUtility.createSuccessPostResponse(JSON.serialize(responseList));
    }
    
    //PATCH METHOD
    public static void updateScheduleSession(String scheduleSessionWrapperDetails){
        updateScheduleSessionWrapper request = (updateScheduleSessionWrapper) JSON.deserialize(
              scheduleSessionWrapperDetails,
              updateScheduleSessionWrapper.class
        );
        Schedule_Sessions__c session = new Schedule_Sessions__c(Id=request.sessionId);
        session.Session_Fee__c = request?.sessionFee;
        session.Start_Date__c = request?.startDate;
        session.End_Date__c = request?.endDate;
        session.Start_Time__c = request?.startTime;
        session.End_Time__c = request?.endTime;
        
        update session;
    }
    public class scheduleSessionWrapper{
        public string Id;
        public string sessionTitle;
        public String agenda;
        public Date startDate;
        public Date endDate;
        public Time startTime;
        public Time endTime;
        public Integer sessionFee;
        public Boolean noFee;
        public String sessionBroucher;
        public Boolean issessionBroucher;
        public String eventReference;
        public String locationType;
        public String locationAddress;
        public String sessionLink;
        public List<SpeakerWrapper> speakers;
        
        public scheduleSessionWrapper() {
            this.speakers = new List<SpeakerWrapper>();
        }
         public Schedule_Sessions__c getRecord() {
            String  sessionBroucherURL=' ';
            this.issessionBroucher = true;
            if((this.sessionBroucher !=null && this.sessionBroucher !='') && this.issessionBroucher){
               sessionBroucherURL = ken42_CreateContentVersion.createContentVersion(this.sessionTitle, this.sessionBroucher);
            }
        	System.debug('sessionBroucherURL==='+sessionBroucherURL);
             Schedule_Sessions__c session = new Schedule_Sessions__c();
             if(this.Id != null && this.Id !=''){
                 
            	session.Id = this.Id;
             }
             if(this.sessionTitle != null && this.sessionTitle !=''){
                 
            	session.Name = this.sessionTitle;
             }
              if(this.agenda != null && this.agenda !=''){
                 session.What_to_Expect_From_Event__c = this.agenda;
             }
              if(sessionBroucherURL != null && string.isNotBlank(sessionBroucherURL)){
                 session.Session_Broucher__c = sessionBroucherURL;
             }
              if(this.startDate != null){
                 session.Start_Date__c = this.startDate;
             }
              if(this.endDate != null){
                 session.End_Date__c = this.endDate;
             }
              if(this.startTime != null){
                 session.Start_Time__c = this.startTime;
             }
              if(this.endTime != null){
                 session.End_Time__c = this.endTime;
             }
              if(this.eventReference != null && this.eventReference !=''){
                 session.Event_Reference__c = this.eventReference;
             }
              if(this.locationType != null && this.locationType !=''){
                 session.Location_Type__c = this.locationType;
             }
              if(this.locationAddress != null && this.locationAddress !=''){
                 session.Location__c = this.locationAddress;
             }
              if(this.sessionLink != null && this.sessionLink !=''){
                 session.Session_Link__c = this.sessionLink; 
             }
              if(this.sessionFee != null){
                 session.Session_Fee__c = this.sessionFee;
             }
              if(this.noFee != null){
                 session.No_Fee__c = this.noFee;
             }
   
            return session;
                    
        }
        
    }
       public class SpeakerWrapper {
        public String Id { get; set; }
        public String speakerName { get; set; }
        public String descriptionAboutTheSpeaker { get; set; }
        public String speakerImage { get; set; }
        // Default Constructor
        public SpeakerWrapper() {}
        
        // Constructor to initialize the name and description from the related record
       /* public SpeakerWrapper(Events_Sessions_Enrollment__c speakerRecord) {
            this.name = speakerRecord.Contact__c != null ? speakerRecord.Contact__r.Name : '';
            this.description = speakerRecord.Description__c != null ? speakerRecord.Description__c : '';
            this.Id = speakerRecord.Id != null ? speakerRecord.Id : null;
            this.contactId = speakerRecord.Contact__c != null ? speakerRecord.Contact__c : null;
        }*/
        public Events_Sessions_Enrollment__c getSessionEnrollmentRecord(){
            
             String  speakerImageURL=' ';
            if(this.speakerImage !=null && string.isNotBlank(this.speakerImage)){
                System.debug('this.speakerImage---'+this.speakerImage);
               speakerImageURL = ken42_CreateContentVersion.createContentVersion('SpeakerImage', this.speakerImage);
                System.debug('this.speakerImageURL---'+speakerImageURL);
            }
            Events_Sessions_Enrollment__c speakerRecord = new Events_Sessions_Enrollment__c();
            if (this.descriptionAboutTheSpeaker != null && this.descriptionAboutTheSpeaker != '') {
                speakerRecord.Description__c = this.descriptionAboutTheSpeaker;
            }
            if (this.Id != null && this.Id != '') {
                speakerRecord.Id = this.Id;
            }
            if (string.isNotBlank(speakerImageURL)) {
                speakerRecord.Speaker_Image__c = speakerImageURL;
            }
            if (this.speakerName != null && this.speakerName != '') {
                speakerRecord.Contact__c = this.speakerName;
            }
            return speakerRecord;
        }
    }
    public class updateScheduleSessionWrapper{
        public Id sessionId;
        public Integer sessionFee;
        public Boolean noFee;
        public Date startDate;
        public Date endDate;
        public Time startTime;
        public Time endTime;
    }
    public class sessionResponse{
        public Id sessionId;
        public String sessionTitle;
        public String sessionImage;
    }
    public class sessionIds {
        public List<String> ids;
    }
    public class getWrapper {
    public List<Schedule_Sessions__c> sessions { get; set; }
    public List<Contact> contacts { get; set; }
    
    public getWrapper(List<Schedule_Sessions__c> sessions, List<Contact> contacts) {
        this.sessions = sessions;
        this.contacts = contacts;
    }
}
}