EventsAlumni/force-app/main/default/objects/Event_Booking__c/Event_Booking__c.object-meta.xml
<CustomObject>
    <label>Event Booking</label>
    <nameField>
        <displayFormat>EB-{00000}</displayFormat>
        <label>Event Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EventsAlumni/force-app/main/default/objects/Event_Booking__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Event Bookings</relationshipLabel>
    <relationshipName>Event_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Booking__c/fields/Billing_Details__c.field-meta.xml
<CustomField>
    <fullName>Billing_Details__c</fullName>
    <label>Billing Details</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Booking__c/fields/Booked_for_No_of_Attendees__c.field-meta.xml
<CustomField>
    <fullName>Booked_for_No_of_Attendees__c</fullName>
    <label>Booked for No of Attendees</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Booking__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Bookings</relationshipLabel>
    <relationshipName>Event_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Booking__c/fields/Event_Booking_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Booking_Id__c</fullName>
    <label>Event Booking Id</label>
    <type>AutoNumber</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Booking__c/fields/Schedule_Sessions_Id__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Sessions_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule/Sessions Id</label>
    <referenceTo>Schedule_Sessions__c</referenceTo>
    <relationshipLabel>Event Bookings (Schedule/Sessions Id)</relationshipLabel>
    <relationshipName>Event_Bookings1</relationshipName>
    <type>Lookup</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Booking__c/fields/Schedules_Sessions__c.field-meta.xml
<CustomField>
    <fullName>Schedules_Sessions__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedules &amp; Sessions</label>
    <referenceTo>Schedule_Sessions__c</referenceTo>
    <relationshipLabel>Event Bookings</relationshipLabel>
    <relationshipName>Event_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Booking__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Notify</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Setting__mdt/Event_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Event Setting</label>
    <pluralLabel>Event Settings</pluralLabel>
</CustomObject>

EventsAlumni/force-app/main/default/objects/Event_Setting__mdt/fields/Is_Account_Based__c.field-meta.xml
<CustomField>
    <fullName>Is_Account_Based__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Account Based</label>
    <type>Checkbox</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Schedule_Sessions__c/Schedule_Sessions__c.object-meta.xml
<CustomObject>
    <label>Schedule &amp; Sessions</label>
    <nameField>
        <label>Schedule/Sessions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule &amp; Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EventsAlumni/force-app/main/default/objects/Schedule_Sessions__c/fields/Event_Reference__c.field-meta.xml
<CustomField>
    <fullName>Event_Reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Reference</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Event_Master__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Event</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Event_Master__c</referenceTo>
    <relationshipName>Schedule_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Schedule_Sessions__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <label>Is Active?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

EventsAlumni/force-app/main/default/objects/Schedule_Sessions__c/fields/Schedule_Sessions_Id__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Sessions_Id__c</fullName>
    <displayFormat>Session#{000}</displayFormat>
    <label>Schedule/Sessions Id</label>
    <type>AutoNumber</type>
</CustomField>

EventsAlumni/force-app/main/default/classes/eventSessionRegistration.cls
@RestResource(urlMapping='/eventBookigRegistration/*')
global with sharing class eventSessionRegistration {
     @HttpGET
    global static List<Event_Booking__c> eventBookingGETMethod(){
        //System.debug(RestContext.request.requestBody.toString());
                 RestRequest req = RestContext.request;
        String eventId = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
         List<Event_Booking__c> eventBookingList = [SELECT Id, Name, Account__c, Billing_Details__c, Booked_for_No_of_Attendees__c, Contact__c, Event_Booking_Id__c, Is_Active__c, Type__c, Schedules_Sessions__c, Schedule_Sessions_Id__c FROM Event_Booking__c WHERE Schedules_Sessions__r.Event_Reference__c =:eventId];
        return eventBookingList;
    }
     @HttpDELETE
    global static void deleteeventRegistrations() {
        // Get the incoming request
        RestRequest req = RestContext.request;
        System.debug('req'+req);
        if (req.requestBody != null) {
            System.debug('req.requestBody'+req.requestBody);
            eventRegistrationIds deleteRecords = (eventRegistrationIds) JSON.deserialize(req.requestBody.toString(), eventRegistrationIds.class);
            System.debug('deleteRecords'+deleteRecords);
            List<Event_Booking__c> eventBookings;
        if (!deleteRecords.ids.isEmpty()) {
             eventBookings = [
                SELECT Id, Name, Account__c, Billing_Details__c, Booked_for_No_of_Attendees__c, 
                       Contact__c, Event_Booking_Id__c, Is_Active__c, Type__c, 
                       Schedules_Sessions__c, Schedule_Sessions_Id__c 
                FROM Event_Booking__c 
                WHERE Id IN :deleteRecords.ids
            ];
        }            
            if (!eventBookings.isEmpty()) {
                delete eventBookings;
            }
            } else {
                
                RestContext.response.statusCode = 400;
                RestContext.response.responseBody = Blob.valueOf('Invalid request: No eventbooking IDs provided.');
            }
    }

     @HttpPOST
    global static void eventBookingPostMethod(){
        System.debug(RestContext.request.requestBody.toString());
        registerEventSession(RestContext.request.requestBody.toString());
    }
    
    public static void registerEventSession(string bookingDetails){
     // List<Event_Booking__c> eventBooking = [SELECT Id, Name, Account__c, Billing_Details__c, Booked_for_No_of_Attendees__c, Contact__c, Event_Booking_Id__c, Is_Active__c, Type__c, Schedules_Sessions__c, Schedule_Sessions_Id__c FROM Event_Booking__c];
        List<Event_Booking__c> eventBookingList = new List<Event_Booking__c>();
        List <registerEventSessionWrapper> responseList = new List<registerEventSessionWrapper>();
        List<Schedule_Sessions__c> sessionList = new List<Schedule_Sessions__c>();   
            List<registerEventSessionWrapper> request;
          try {
             request = (List<registerEventSessionWrapper>) JSON.deserialize(
                bookingDetails,
                List<registerEventSessionWrapper>.class
                );
            } catch (Exception e) {
                System.debug('Error deserializing JSON: ' + e.getMessage());
                throw new IllegalArgumentException('Invalid JSON format: ' + e.getMessage());
            }
        
            for(registerEventSessionWrapper eachBooking:request){
                Event_Booking__c eventBooking = eachBooking.getRecord();
                eventBookingList.add(eventBooking);
            }
            if(!eventBookingList.isEmpty()){
                insert eventBookingList;
            }
            for(Event_Booking__c eventBooking:eventBookingList){
                 registerEventSessionWrapper response = new registerEventSessionWrapper();
                response.sessionId = eventBooking.Schedules_Sessions__c;
                response.numberOfAttendees = eventBooking.Booked_for_No_of_Attendees__c;
                response.accountId = eventBooking.Account__c;
                response.contactId = eventBooking.Contact__c;
                responseList.add(response);
            }
        	RestApiUtility.createSuccessPostResponse(JSON.serialize(responseList));
    	}
    
    public class registerEventSessionWrapper{
        public Decimal numberOfAttendees;
        public string sessionId;
        public string Id;
        public string AccountOrContactId;
        public string accountId;
        public string contactId;
        public registerEventSessionWrapper(){
            
        }
        
        public Event_Booking__c getRecord(){
            //EventBookingRegistration__c customSetting = [SELECT Id, Is_Account_Based__c, Name, SetupOwnerId FROM EventBookingRegistration__c Limit 1];
            Event_Setting__mdt customSetting = [SELECT Id, DeveloperName, Label, Is_Account_Based__c FROM Event_Setting__mdt WHERE label ='EventRegistration' Limit 1];
            Event_Booking__c eventBooking = new Event_Booking__c();
            
            if(this.numberOfAttendees !=null){
                eventBooking.Booked_for_No_of_Attendees__c = this.numberOfAttendees;
            }
            if(string.isNotBlank(this.sessionId)){
                eventBooking.Schedules_Sessions__c = this.sessionId;
            }   
            if(string.isNotBlank(this.AccountOrContactId) && customSetting?.Is_Account_Based__c == true){
                eventBooking.Account__c = this.AccountOrContactId;
            }
            else if(string.isNotBlank(this.AccountOrContactId)){
                eventBooking.Contact__c = this.AccountOrContactId;
            } 
            return eventBooking;
        }
    }
    
    public class eventRegistrationIds {
        public List<String> ids;
    }
}