EventsAlumni/force-app/main/default/objects/Event_Booking__c/Event_Booking__c.object-meta.xml
<CustomObject>
    <label>Event Booking</label>
    <nameField>
        <displayFormat>EB-{00000}</displayFormat>
        <label>Event Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EventsAlumni/force-app/main/default/objects/Event_Booking__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Event Bookings</relationshipLabel>
    <relationshipName>Event_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Booking__c/fields/Billing_Details__c.field-meta.xml
<CustomField>
    <fullName>Billing_Details__c</fullName>
    <label>Billing Details</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Booking__c/fields/Booked_for_No_of_Attendees__c.field-meta.xml
<CustomField>
    <fullName>Booked_for_No_of_Attendees__c</fullName>
    <label>Booked for No of Attendees</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Booking__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Bookings</relationshipLabel>
    <relationshipName>Event_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Booking__c/fields/Event_Booking_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Booking_Id__c</fullName>
    <label>Event Booking Id</label>
    <type>AutoNumber</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Booking__c/fields/Schedule_Sessions_Id__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Sessions_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedule/Sessions Id</label>
    <referenceTo>Schedule_Sessions__c</referenceTo>
    <relationshipLabel>Event Bookings (Schedule/Sessions Id)</relationshipLabel>
    <relationshipName>Event_Bookings1</relationshipName>
    <type>Lookup</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Booking__c/fields/Schedules_Sessions__c.field-meta.xml
<CustomField>
    <fullName>Schedules_Sessions__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schedules &amp; Sessions</label>
    <referenceTo>Schedule_Sessions__c</referenceTo>
    <relationshipLabel>Event Bookings</relationshipLabel>
    <relationshipName>Event_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Booking__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Notify</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Master__c/Event_Master__c.object-meta.xml
<CustomObject>
    <label>Event Master</label>
    <nameField>
        <label>Events/Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Master Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EventsAlumni/force-app/main/default/objects/Event_Master__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Master Setup</relationshipLabel>
    <relationshipName>Event_Master_Setup</relationshipName>
    <type>Lookup</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Master__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active?</label>
    <type>Checkbox</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Master__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <label>Event</label>
</RecordType>

EventsAlumni/force-app/main/default/objects/Event_Setting__mdt/Event_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Event Setting</label>
    <pluralLabel>Event Settings</pluralLabel>
</CustomObject>

EventsAlumni/force-app/main/default/objects/Event_Setting__mdt/fields/Is_Account_Based__c.field-meta.xml
<CustomField>
    <fullName>Is_Account_Based__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Account Based</label>
    <type>Checkbox</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Schedule_Sessions__c/Schedule_Sessions__c.object-meta.xml
<CustomObject>
    <label>Schedule &amp; Sessions</label>
    <nameField>
        <label>Schedule/Sessions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule &amp; Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EventsAlumni/force-app/main/default/objects/Schedule_Sessions__c/fields/Event_Reference__c.field-meta.xml
<CustomField>
    <fullName>Event_Reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Reference</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Event_Master__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Event</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Event_Master__c</referenceTo>
    <relationshipName>Schedule_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Schedule_Sessions__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <label>Is Active?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

EventsAlumni/force-app/main/default/objects/Schedule_Sessions__c/fields/Schedule_Sessions_Id__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Sessions_Id__c</fullName>
    <displayFormat>Session#{000}</displayFormat>
    <label>Schedule/Sessions Id</label>
    <type>AutoNumber</type>
</CustomField>

EventsAlumni/force-app/main/default/classes/eventSessionRegistrationTest.cls
@isTest
public class eventSessionRegistrationTest {
    
    @isTest
    public static void testEventBookingGETMethod() {
        
        Event_Master__c em = new Event_Master__c(Name = 'Test');
        insert em;
        
        Account acc = new Account(Name = 'Test');
        insert acc;
        
        Contact con = new Contact(LastName = 'Test');
        insert con;
        
        Schedule_Sessions__c ss = new Schedule_Sessions__c(Name = 'Test', Event_Reference__c = em.Id);
        insert ss;
        // Create test data for Event_Booking__c
        Event_Booking__c eventBooking = new Event_Booking__c(
            //Name = 'Test Event Booking',
            Account__c = acc.Id,
            Billing_Details__c = 'Test Billing',
            Booked_for_No_of_Attendees__c = 10,
            Contact__c = con.Id,
            //Event_Booking_Id__c = 'EVT001',
            Is_Active__c = true,
            Type__c = 'Registered',
            Schedules_Sessions__c = ss.Id,
            Schedule_Sessions_Id__c = ss.Id
        );
        insert eventBooking;
        
        Test.startTest();
        
        // Prepare the REST API request with the Event ID
        RestContext.request = new RestRequest();
        RestContext.request.requestUri = '/services/apexrest/eventBookigRegistration/' + em.Id;
        RestContext.request.httpMethod = 'GET';
        
        // Call the method and assert the results
        List<Event_Booking__c> result = eventSessionRegistration.eventBookingGETMethod();
        
        Test.stopTest();
        
        // Assert that the event booking data is returned
        System.assertEquals(1, result.size());
        System.assertEquals(eventBooking.Id, result[0].Id);
    }
    
    @isTest
    public static void testDeleteEventRegistrations() {
        
        Event_Master__c em = new Event_Master__c(Name = 'Test');
        insert em;
        
        Account acc = new Account(Name = 'Test');
        insert acc;
        
        Contact con = new Contact(LastName = 'Test');
        insert con;
        
        Schedule_Sessions__c ss = new Schedule_Sessions__c(Name = 'Test', Event_Reference__c = em.Id);
        insert ss;
        // Create test data for Event_Booking__c
        Event_Booking__c eventBooking1 = new Event_Booking__c(
            //Name = 'Test Event Booking 1',
            Account__c = acc.Id,
            Billing_Details__c = 'Test Billing',
            Booked_for_No_of_Attendees__c = 10,
            Contact__c = con.Id,
            //Event_Booking_Id__c = 'EVT002',
            Is_Active__c = true,
            Type__c = 'Registered',
            Schedules_Sessions__c = ss.Id,
            Schedule_Sessions_Id__c = ss.Id
        );
        insert eventBooking1;
        
        Schedule_Sessions__c ss2 = new Schedule_Sessions__c(Name = 'Test2', Event_Reference__c = em.Id);
        insert ss2;
        
        Event_Booking__c eventBooking2 = new Event_Booking__c(
            //Name = 'Test Event Booking 2',
            Account__c = acc.Id,
            Billing_Details__c = 'Test Billing',
            Booked_for_No_of_Attendees__c = 15,
            Contact__c = con.Id,
            //Event_Booking_Id__c = 'EVT003',
            Is_Active__c = true,
            Type__c = 'Registered',
            Schedules_Sessions__c = ss2.Id,
            Schedule_Sessions_Id__c = ss2.Id
        );
        insert eventBooking2;
        
        // Prepare the request to delete the event bookings
        eventSessionRegistration.eventRegistrationIds deleteIds = new eventSessionRegistration.eventRegistrationIds();
        deleteIds.ids = new List<String>{ eventBooking1.Id, eventBooking2.Id };
            
            String body = JSON.serialize(deleteIds);
        
        Test.startTest();
        
        // Simulate the DELETE request
        RestContext.request = new RestRequest();
        RestContext.request.requestBody = Blob.valueOf(body);
        RestContext.request.httpMethod = 'DELETE';
        
        // Call the delete method
        eventSessionRegistration.deleteeventRegistrations();
        
        Test.stopTest();
        
        // Verify that the event bookings were deleted
        // Query for the deleted bookings
        List<Event_Booking__c> deletedBooking1List = [SELECT Id FROM Event_Booking__c WHERE Id = :eventBooking1.Id LIMIT 1];
        List<Event_Booking__c> deletedBooking2List = [SELECT Id FROM Event_Booking__c WHERE Id = :eventBooking2.Id LIMIT 1];
        
        // Assert that no records were returned, indicating they were deleted
        System.assertEquals(0, deletedBooking1List.size(), 'Event_Booking__c record with Id ' + eventBooking1.Id + ' was not deleted.');
        System.assertEquals(0, deletedBooking2List.size(), 'Event_Booking__c record with Id ' + eventBooking2.Id + ' was not deleted.');
        
    }
    
    @isTest
    public static void testEventBookingPostMethod() {
        // Create test data for Account, Contact, and Schedule_Sessions__c
        Account acc = new Account(Name = 'Test Account');
        insert acc;
        
        Contact con = new Contact(LastName = 'Test Contact');
        insert con;
        
        Event_Master__c em = new Event_Master__c(Name = 'Test Event Master');
        insert em;
        
        Schedule_Sessions__c ss = new Schedule_Sessions__c(Name = 'Test Schedule', Event_Reference__c = em.Id);
        insert ss;
        
        // Create a mock request body for the POST method
        // Here we use the Ids of the previously inserted records (Schedule_Sessions__c and Account)
       /* EventBookingRegistration__c customSetting = new EventBookingRegistration__c(
            Name = 'Test Setting',
            Is_Account_Based__c = true,
            SetupOwnerId = UserInfo.getUserId()  // Use the current user ID
        );
        insert customSetting;*/
        //Event_Setting__mdt  customSetting = [SELECT Id, DeveloperName, Label, Is_Account_Based__c FROM Event_Setting__mdt WHERE label ='EventRegistration'];
        String requestBody = '[{"numberOfAttendees": 5, "sessionId": "' + ss.Id + '", "AccountOrContactId": "' + con.Id + '"}]';
        
        Test.startTest();
        
        // Simulate the POST request
        RestContext.request = new RestRequest();
        RestContext.request.requestBody = Blob.valueOf(requestBody);
        RestContext.request.httpMethod = 'POST';
        
        // Call the POST method
        eventSessionRegistration.eventBookingPostMethod();
        
        Test.stopTest();
        
        // Verify that the event booking was inserted
        List<Event_Booking__c> eventBookings = [SELECT Id, Booked_for_No_of_Attendees__c FROM Event_Booking__c WHERE Contact__c = :con.Id];
        
        System.assertEquals(1, eventBookings.size());
        System.assertEquals(5, eventBookings[0].Booked_for_No_of_Attendees__c);
    }
}