NewFlameHM/force-app/main/default/objects/Account/recordTypes/Mess.recordType-meta.xml
<RecordType>
    <fullName>Mess</fullName>
    <active>true</active>
    <label>Mess</label>
</RecordType>

NewFlameHM/force-app/main/default/objects/Menu__c/Menu__c.object-meta.xml
<CustomObject>
    <label>Menu</label>
    <nameField>
        <label>Menu Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Menus</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NewFlameHM/force-app/main/default/objects/Menu__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Breakfast</fullName>
            </value>
            <value>
                <fullName>Lunch</fullName>
            </value>
            <value>
                <fullName>Snacks</fullName>
            </value>
            <value>
                <fullName>Dinner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NewFlameHM/force-app/main/default/objects/Menu__c/fields/Day__c.field-meta.xml
<CustomField>
    <fullName>Day__c</fullName>
    <label>Day</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sunday</fullName>
            </value>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NewFlameHM/force-app/main/default/objects/Menu__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Breakfast</fullName>
            </value>
            <value>
                <fullName>Lunch</fullName>
            </value>
            <value>
                <fullName>Snacks</fullName>
            </value>
            <value>
                <fullName>Dinner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NewFlameHM/force-app/main/default/objects/Menu_Order__c/Menu_Order__c.object-meta.xml
<CustomObject>
    <label>Schedule</label>
    <nameField>
        <label>Menu Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NewFlameHM/force-app/main/default/objects/Menu_Order__c/fields/Day__c.field-meta.xml
<CustomField>
    <fullName>Day__c</fullName>
    <label>Day</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sunday</fullName>
            </value>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NewFlameHM/force-app/main/default/objects/Menu_Order__c/fields/Menu_Id__c.field-meta.xml
<CustomField>
    <fullName>Menu_Id__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Menu Id</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Menu__c.Approval_Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Menu__c</referenceTo>
    <relationshipName>Menu_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

NewFlameHM/force-app/main/default/objects/Menu_Order__c/fields/Mess__c.field-meta.xml
<CustomField>
    <fullName>Mess__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Mess</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Mess</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Menu_Orders2</relationshipName>
    <type>Lookup</type>
</CustomField>

NewFlameHM/force-app/main/default/classes/WeeklyMenuController.cls
/**
 * Controller for Weekly Menu LWC Component
 * Provides methods to fetch menu data based on mess ID and date range
 */
public without sharing class WeeklyMenuController {
    
    /**
     * Get weekly menu data for a specific mess and date range
     * @param messId - ID of the mess
     * @param startDate - Start date of the week (YYYY-MM-DD)
     * @return List<Menu_Order__c> - List of menu order records
     */
    @AuraEnabled(cacheable=true)
    public static List<Menu_Order__c> getWeeklyMenu(String messId, String startDate) {
        try {
            // Parse the start date
            Date weekStart = Date.valueOf(startDate);
            
            // Calculate the end date (add 6 days to include the full week)
            Date weekEnd = weekStart.addDays(6);
            
            System.debug('Date range: ' + weekStart + ' to ' + weekEnd);
            System.debug('mess id::' + messId);
            
            // Query for the menu items
            List<Menu_Order__c> menuItems = [
                SELECT 
                    Id, 
                    Name, 
                    Day__c,
                    Type__c,
                    Date__c,
                    Start_Time__c,
                    End_Time__c, 
                    Menu_Id__r.Name, 
                    Mess__r.Name,
                    Item__c,
                    Category__c,
                    CreatedDate,
                    LastModifiedDate 
                FROM 
                    Menu_Order__c 
                WHERE 
                    RecordType.Name = 'Daily Menu' 
                    AND Mess__c = :messId
                    AND Date__c >= :weekStart
                    AND Date__c <= :weekEnd
                ORDER BY 
                    Date__c ASC, 
                    Type__c ASC, 
                    Category__c ASC
            ];

            System.debug('menuItems size:::' + menuItems.size());
            
            return menuItems;
        } catch (Exception e) {
            throw new AuraHandledException('Error retrieving menu data: ' + e.getMessage());
        }
    }
}