NewFlameHM/force-app/main/default/objects/Account/recordTypes/Mess.recordType-meta.xml
<RecordType>
    <fullName>Mess</fullName>
    <active>true</active>
    <label>Mess</label>
</RecordType>

NewFlameHM/force-app/main/default/objects/Menu__c/Menu__c.object-meta.xml
<CustomObject>
    <label>Menu</label>
    <nameField>
        <label>Menu Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Menus</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NewFlameHM/force-app/main/default/objects/Menu__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NewFlameHM/force-app/main/default/objects/Menu__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Breakfast</fullName>
            </value>
            <value>
                <fullName>Lunch</fullName>
            </value>
            <value>
                <fullName>Snacks</fullName>
            </value>
            <value>
                <fullName>Dinner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NewFlameHM/force-app/main/default/objects/Menu__c/fields/Day__c.field-meta.xml
<CustomField>
    <fullName>Day__c</fullName>
    <label>Day</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sunday</fullName>
            </value>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NewFlameHM/force-app/main/default/objects/Menu__c/fields/Meal_Type__c.field-meta.xml
<CustomField>
    <fullName>Meal_Type__c</fullName>
    <label>Meal Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Veg</fullName>
            </value>
            <value>
                <fullName>Non Veg</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NewFlameHM/force-app/main/default/objects/Menu__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Breakfast</fullName>
            </value>
            <value>
                <fullName>Lunch</fullName>
            </value>
            <value>
                <fullName>Snacks</fullName>
            </value>
            <value>
                <fullName>Dinner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NewFlameHM/force-app/main/default/objects/Menu_Item__c/Menu_Item__c.object-meta.xml
<CustomObject>
    <label>Food Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Food Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NewFlameHM/force-app/main/default/objects/Menu_Item__c/fields/Calories_kcal__c.field-meta.xml
<CustomField>
    <fullName>Calories_kcal__c</fullName>
    <label>Calories (kcal)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NewFlameHM/force-app/main/default/objects/Menu_Item__c/fields/Carbs__c.field-meta.xml
<CustomField>
    <fullName>Carbs__c</fullName>
    <label>Carbs</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NewFlameHM/force-app/main/default/objects/Menu_Item__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accompaniment</fullName>
            </value>
            <value>
                <fullName>Beverage</fullName>
            </value>
            <value>
                <fullName>Bread</fullName>
            </value>
            <value>
                <fullName>Cereal</fullName>
            </value>
            <value>
                <fullName>Chutney</fullName>
            </value>
            <value>
                <fullName>Cold Beverage</fullName>
            </value>
            <value>
                <fullName>Curd</fullName>
            </value>
            <value>
                <fullName>Dal</fullName>
            </value>
            <value>
                <fullName>Dessert</fullName>
            </value>
            <value>
                <fullName>Dry Veg</fullName>
            </value>
            <value>
                <fullName>Fruits/Juice</fullName>
            </value>
            <value>
                <fullName>Gravy Veg</fullName>
            </value>
            <value>
                <fullName>Hot Beverage</fullName>
            </value>
            <value>
                <fullName>Indian Breakfast</fullName>
            </value>
            <value>
                <fullName>Jain Dry</fullName>
            </value>
            <value>
                <fullName>Main</fullName>
            </value>
            <value>
                <fullName>Milk</fullName>
            </value>
            <value>
                <fullName>Papad/Fryums</fullName>
            </value>
            <value>
                <fullName>Papad / Fryums</fullName>
            </value>
            <value>
                <fullName>Pickle</fullName>
            </value>
            <value>
                <fullName>Preserves</fullName>
            </value>
            <value>
                <fullName>Rice</fullName>
            </value>
            <value>
                <fullName>Roti</fullName>
            </value>
            <value>
                <fullName>Salad</fullName>
            </value>
            <value>
                <fullName>Side Dish</fullName>
            </value>
            <value>
                <fullName>Snacks</fullName>
            </value>
            <value>
                <fullName>Soup</fullName>
            </value>
            <value>
                <fullName>Spread</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NewFlameHM/force-app/main/default/objects/Menu_Item__c/fields/Cholesterol__c.field-meta.xml
<CustomField>
    <fullName>Cholesterol__c</fullName>
    <label>Cholesterol</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NewFlameHM/force-app/main/default/objects/Menu_Item__c/fields/Cuisine__c.field-meta.xml
<CustomField>
    <fullName>Cuisine__c</fullName>
    <label>Cuisine</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>Gujarati</fullName>
            </value>
            <value>
                <fullName>Indian</fullName>
            </value>
            <value>
                <fullName>Korean</fullName>
            </value>
            <value>
                <fullName>Maharashtrian</fullName>
            </value>
            <value>
                <fullName>North Indian</fullName>
            </value>
            <value>
                <fullName>Punjabi</fullName>
            </value>
            <value>
                <fullName>South Indian</fullName>
            </value>
            <value>
                <fullName>Western</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NewFlameHM/force-app/main/default/objects/Menu_Item__c/fields/Fat__c.field-meta.xml
<CustomField>
    <fullName>Fat__c</fullName>
    <label>Fat</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NewFlameHM/force-app/main/default/objects/Menu_Item__c/fields/Fibre__c.field-meta.xml
<CustomField>
    <fullName>Fibre__c</fullName>
    <label>Fibre</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NewFlameHM/force-app/main/default/objects/Menu_Item__c/fields/Meal_Type__c.field-meta.xml
<CustomField>
    <fullName>Meal_Type__c</fullName>
    <label>Meal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Veg</fullName>
            </value>
            <value>
                <fullName>Non Veg</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NewFlameHM/force-app/main/default/objects/Menu_Item__c/fields/Protein__c.field-meta.xml
<CustomField>
    <fullName>Protein__c</fullName>
    <label>Protein</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NewFlameHM/force-app/main/default/objects/Menu_Item__c/fields/Sugar__c.field-meta.xml
<CustomField>
    <fullName>Sugar__c</fullName>
    <label>Sugar</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

NewFlameHM/force-app/main/default/objects/Menu_Order__c/Menu_Order__c.object-meta.xml
<CustomObject>
    <label>Schedule</label>
    <nameField>
        <label>Menu Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NewFlameHM/force-app/main/default/objects/Menu_Order__c/fields/Day__c.field-meta.xml
<CustomField>
    <fullName>Day__c</fullName>
    <label>Day</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sunday</fullName>
            </value>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NewFlameHM/force-app/main/default/objects/Menu_Order__c/fields/Menu_Id__c.field-meta.xml
<CustomField>
    <fullName>Menu_Id__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Menu Id</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Menu__c.Approval_Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Menu__c</referenceTo>
    <relationshipName>Menu_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

NewFlameHM/force-app/main/default/objects/Menu_Order__c/fields/Mess__c.field-meta.xml
<CustomField>
    <fullName>Mess__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Mess</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Mess</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Menu_Orders2</relationshipName>
    <type>Lookup</type>
</CustomField>

NewFlameHM/force-app/main/default/classes/DailyMenuController.cls
public without sharing class DailyMenuController {

    @AuraEnabled(cacheable=true)
    public static List<Menu_Order__c> getDailyMenu(String messId, String selectedDate) {
        try {
            // Validate inputs
            if (String.isBlank(messId) || String.isBlank(selectedDate)) {
                throw new AuraHandledException('Mess ID and Date are required.');
            }
            
            // Parse date
            Date menuDate = Date.valueOf(selectedDate);

            System.debug('menuDate is ::' + menuDate);
            //System.debug('menuDate typeof:::' +  menuDate instanceof Date);
            System.debug('messId is ::' + messId);
            
            // Query menu items
            return [
                SELECT 
                    Id, Name, Day__c, Type__c,Menu_Id__r.Approval_Status__c, Date__c, Start_Time__c, End_Time__c, 
                    Menu_Id__r.Name, Mess__r.Name, Item__c, Category__c, 
                    CreatedDate, LastModifiedDate
                FROM Menu_Order__c 
                WHERE RecordType.Name = 'Daily Menu' 
                AND Mess__c = :messId 
                AND Date__c = :menuDate
                AND Menu_Id__r.Approval_Status__c = 'Approved'
                ORDER BY Type__c, Name
            ];
        } catch (Exception e) {
            throw new AuraHandledException('Error retrieving menu data: ' + e.getMessage());
        }
    }
    
    /**
     * Retrieves menu item details by item names
     * @param itemNames List of item names to look up
     * @return List of Menu_Item__c records
     */
    @AuraEnabled(cacheable=true)
    public static List<Menu_Item__c> getMenuItemDetails(List<String> itemNames) {
        try {
            // Validate input
            if (itemNames == null || itemNames.isEmpty()) {
                return new List<Menu_Item__c>();
            }
            
            // Query menu item details
            return [
                SELECT 
                    Id, Name, Calories_kcal__c, Carbs__c, Category__c, 
                    Cholesterol__c, Cuisine__c, Fat__c, Fibre__c, 
                    Sugar__c, Protein__c,Meal_Type__c
                FROM Menu_Item__c
                WHERE Name IN :itemNames
            ];
        } catch (Exception e) {
            throw new AuraHandledException('Error retrieving menu item details: ' + e.getMessage());
        }
    }
    
}