EventsAlumni/force-app/main/default/objects/Event_Master__c/Event_Master__c.object-meta.xml
<CustomObject>
    <label>Event Master</label>
    <nameField>
        <label>Events/Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Master Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EventsAlumni/force-app/main/default/objects/Event_Master__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <label>Event</label>
</RecordType>

EventsAlumni/force-app/main/default/objects/Event_Target_Audience__c/Event_Target_Audience__c.object-meta.xml
<CustomObject>
    <label>Event Target Audience</label>
    <nameField>
        <displayFormat>ETA-{000000}</displayFormat>
        <label>Event Target Audience Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Target Audiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EventsAlumni/force-app/main/default/objects/Event_Target_Audience__c/fields/Event_Master__c.field-meta.xml
<CustomField>
    <fullName>Event_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Master</label>
    <referenceTo>Event_Master__c</referenceTo>
    <relationshipLabel>Event Target Audiences</relationshipLabel>
    <relationshipName>Event_Target_Audiences</relationshipName>
    <type>Lookup</type>
</CustomField>

EventsAlumni/force-app/main/default/objects/Event_Target_Audience__c/fields/Invite_All__c.field-meta.xml
<CustomField>
    <fullName>Invite_All__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Invite All</label>
    <type>Checkbox</type>
</CustomField>

EventsAlumni/force-app/main/default/classes/EventTargetAudience_Test.cls
@IsTest
public class EventTargetAudience_Test {
@TestSetup
    static void testData(){
        /*** Insert Event ***/
        Event_Master__c event = new Event_Master__c(Name = 'Test Event');
        insert event;
        
        /*** Insert Contact ***/
        Contact contact = new Contact();
        contact.FirstName = 'Test';
        contact.LastName = 'Contact';
        contact.Event_Reminder_Email_Id__c = 'TestContact@yopmail.com';
        
        insert contact;
    }
    @IsTest
    static void testEventTargetAudience(){
        List<Event_Master__c> event = [SELECT Id, Name FROM Event_Master__c LIMIT 1];
        
        System.assertEquals(1,event.size());
        Event_Target_Audience__c ETA = new Event_Target_Audience__c();
        ETA.Invite_All__c = true;
        ETA.Event_Master__c = event[0].Id;
        insert ETA;
        Event_Target_Audience__c insertedETA = [SELECT Id, Invite_All__c FROM Event_Target_Audience__c WHERE Id = :ETA.Id];
        
        System.assertEquals(true, insertedETA.Invite_All__c, 'The Invite_All field should be true.');
    }
}