NewFlameHM/force-app/main/default/objects/Menu__c/Menu__c.object-meta.xml
<CustomObject>
    <label>Menu</label>
    <nameField>
        <label>Menu Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Menus</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NewFlameHM/force-app/main/default/objects/Menu__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NewFlameHM/force-app/main/default/objects/Menu__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Breakfast</fullName>
            </value>
            <value>
                <fullName>Lunch</fullName>
            </value>
            <value>
                <fullName>Snacks</fullName>
            </value>
            <value>
                <fullName>Dinner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NewFlameHM/force-app/main/default/objects/Menu__c/fields/Day__c.field-meta.xml
<CustomField>
    <fullName>Day__c</fullName>
    <label>Day</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sunday</fullName>
            </value>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NewFlameHM/force-app/main/default/objects/Menu__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Breakfast</fullName>
            </value>
            <value>
                <fullName>Lunch</fullName>
            </value>
            <value>
                <fullName>Snacks</fullName>
            </value>
            <value>
                <fullName>Dinner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NewFlameHM/force-app/main/default/objects/Menu_Order__c/Menu_Order__c.object-meta.xml
<CustomObject>
    <label>Schedule</label>
    <nameField>
        <label>Menu Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

NewFlameHM/force-app/main/default/objects/Menu_Order__c/fields/Day__c.field-meta.xml
<CustomField>
    <fullName>Day__c</fullName>
    <label>Day</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sunday</fullName>
            </value>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

NewFlameHM/force-app/main/default/objects/Menu_Order__c/fields/Menu_Id__c.field-meta.xml
<CustomField>
    <fullName>Menu_Id__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Menu Id</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Menu__c.Approval_Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Menu__c</referenceTo>
    <relationshipName>Menu_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

NewFlameHM/force-app/main/default/objects/Menu_Order__c/fields/Mess__c.field-meta.xml
<CustomField>
    <fullName>Mess__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Mess</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Mess</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Menu_Orders2</relationshipName>
    <type>Lookup</type>
</CustomField>

NewFlameHM/force-app/main/default/objects/Menu_Order__c/recordTypes/Template.recordType-meta.xml
<RecordType>
    <fullName>Template</fullName>
    <active>true</active>
    <label>Template</label>
</RecordType>

NewFlameHM/force-app/main/default/classes/MessMenuControllerForStudent.cls
public without sharing class MessMenuControllerForStudent {
    @AuraEnabled(cacheable=true)
    public static List<Menu_Order__c> getMessSchedule(String messId) {
        return [SELECT Id, Name, RecordTypeId, Start_Time__c, End_Time__c, Day__c, Type__c 
                FROM Menu_Order__c 
                WHERE RecordType.Name = 'Template' 
                AND Mess__c  = :messId];
    }
    @AuraEnabled(cacheable=true)
    public static List<Menu_Order__c> getDailyMenuItemsStudentPortal(String messId, Date startDate, Date endDate,Long refreshToken) {
        // Query for daily menu records within date range
        return [SELECT Id, Name, Day__c,Menu_Id__r.Approval_Status__c, Date__c, Type__c, Category__c, Item__c, Start_Time__c, End_Time__c, Mess__c
                FROM Menu_Order__c
                WHERE RecordType.Name = 'Daily Menu'
                AND Mess__c = :messId
                AND Date__c >= :startDate
                AND Date__c <= :endDate
                AND Menu_Id__r.Approval_Status__c = 'Approved'
                ORDER BY Date__c, Type__c, Category__c];
    } 
    
}